config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root 'transactions#index'
  post '/import', to: 'transactions#import'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item_level.rb
class ItemLevel < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  def self.import_csv(incoming_file)
    dir = Rails.root.join('public/uploads')
    Dir.mkdir(dir) unless Dir.exist?(dir)
    file_name = "#{DateTime.now.strftime('%d%m%Y%H%M')}_file.csv"
    File.open(dir.join(file_name), 'wb') do |file|
      file.write(incoming_file.read)
    end
    CsvImportJob.perform_async(dir.join(file_name).to_s)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = Transaction.joins("LEFT OUTER JOIN item_levels ON transactions.section_code = item_levels.item_number")
    .where("destination_zone IN (?) AND (action_code LIKE 'Подбор%' AND operation_code LIKE 'Подбор%')", ['RDT Devices', 'Устройства радиопередачи'])
    .select("transactions.wh, transactions.user_name,
            COUNT(DISTINCT CASE WHEN item_levels.level IS NULL THEN CONCAT(transactions.box_number, transactions.lpn_destination) END) AS count,
            COUNT(DISTINCT CASE WHEN item_levels.level = 'ПЛИТКА' THEN CONCAT(transactions.box_number, transactions.lpn_destination) END) AS count_plitka,
            COUNT(DISTINCT CASE WHEN item_levels.level IN ('ЛИСТОВЫЕ МАТЕРИАЛЫ', 'ГИПСОКАРТОН') THEN CONCAT(transactions.box_number, transactions.lpn_destination) END) AS count_listovye")
    .group("transactions.wh, transactions.user_name")
  end

  def import
    incoming_file = params[:file]
    return redirect_to root_path unless incoming_file

    Transaction.import_csv(incoming_file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar bg-dark navbar-expand-lg bg-body-tertiary sticky-top">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Navbar</a>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <title>Qs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'navbar' %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/transactions/index.html.erb
<%= form_with url: import_path, method: :post do |f| %>
  <%= f.file_field :file, accept: '.csv' %>
  <%= f.submit 'dsfsdf', class: 'btn btn-primary' %>
<% end %>

<table class="table table-sm">
  <thead>
    <tr>
      <% @transactions.first.attributes.keys.each do |column_name| %>
        <th><%= column_name.humanize %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <% transaction.attributes.values.each do |value| %>
          <td><%= value %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>